# Generated by Django 3.2.3 on 2021-11-30 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_usuarios_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
