# Generated by Django 3.2.3 on 2021-11-30 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_usuarios_fecha_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='edad',
        ),
    ]
