# Generated by Django 3.2.3 on 2021-11-30 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_usuarios_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='convocatorias',
            name='fecha_creacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='convocatorias',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
