# Generated by Django 3.2.3 on 2021-11-30 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20211130_0036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postulaciones',
            old_name='postulante',
            new_name='aspirante',
        ),
    ]
