# Generated by Django 3.2.3 on 2021-12-14 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_postulaciones_aspirante'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencias',
            name='cargo',
            field=models.CharField(default='', max_length=255),
        ),
    ]
