# Generated by Django 3.2.3 on 2021-12-14 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_postulaciones_aspirante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulaciones',
            name='aspirante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.cuentas'),
        ),
        migrations.AlterField(
            model_name='postulaciones',
            name='convocatoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.convocatorias'),
        ),
    ]
