# Generated by Django 3.2.3 on 2022-06-09 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20211214_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='genero',
            field=models.CharField(default='m', max_length=1),
        ),
    ]
