# Generated by Django 3.2.3 on 2022-06-09 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20220609_0032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivos',
            name='extension',
        ),
        migrations.RemoveField(
            model_name='archivos',
            name='nombre_archivo',
        ),
    ]
